// Implementation file for parser generated by fsyacc
module Parser

#nowarn "64" // turn off warnings that type variables used in production annotations are instantiated to concrete type

open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers

open Language

// This type is the type of tokens accepted by the parser
type token =
  | EOF
  | IDENT of (string)
  | BAR
  | EQUAL
  | TYPE
  | MODULE
  | PUB
  | OPEN
  | TH
  | AX
  | SQUARE
  | PROOF
  | COMMA
  | RIGHT_BRACE
  | LEFT_BRACE
  | RIGHT_PAREN
  | LEFT_PAREN
  | NOT
  | DIFFERS
  | EQUIVALES
  | FOLLOWS
  | IMPLIES
  | OR
  | AND
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId =
  | TOKEN_EOF
  | TOKEN_IDENT
  | TOKEN_BAR
  | TOKEN_EQUAL
  | TOKEN_TYPE
  | TOKEN_MODULE
  | TOKEN_PUB
  | TOKEN_OPEN
  | TOKEN_TH
  | TOKEN_AX
  | TOKEN_SQUARE
  | TOKEN_PROOF
  | TOKEN_COMMA
  | TOKEN_RIGHT_BRACE
  | TOKEN_LEFT_BRACE
  | TOKEN_RIGHT_PAREN
  | TOKEN_LEFT_PAREN
  | TOKEN_NOT
  | TOKEN_DIFFERS
  | TOKEN_EQUIVALES
  | TOKEN_FOLLOWS
  | TOKEN_IMPLIES
  | TOKEN_OR
  | TOKEN_AND
  | TOKEN_end_of_input
  | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId =
  | NONTERM__startstart
  | NONTERM_expr
  | NONTERM_identList
  | NONTERM_hintOp
  | NONTERM_hint
  | NONTERM_transformer
  | NONTERM_steps
  | NONTERM_proof
  | NONTERM_law
  | NONTERM_open
  | NONTERM_valueList
  | NONTERM_typeDecl
  | NONTERM_statement
  | NONTERM_statements
  | NONTERM_module
  | NONTERM_start

// This function maps tokens to integer indexes
let tagOfToken (t: token) =
  match t with
  | EOF -> 0
  | IDENT _ -> 1
  | BAR -> 2
  | EQUAL -> 3
  | TYPE -> 4
  | MODULE -> 5
  | PUB -> 6
  | OPEN -> 7
  | TH -> 8
  | AX -> 9
  | SQUARE -> 10
  | PROOF -> 11
  | COMMA -> 12
  | RIGHT_BRACE -> 13
  | LEFT_BRACE -> 14
  | RIGHT_PAREN -> 15
  | LEFT_PAREN -> 16
  | NOT -> 17
  | DIFFERS -> 18
  | EQUIVALES -> 19
  | FOLLOWS -> 20
  | IMPLIES -> 21
  | OR -> 22
  | AND -> 23

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx: int) =
  match tokenIdx with
  | 0 -> TOKEN_EOF
  | 1 -> TOKEN_IDENT
  | 2 -> TOKEN_BAR
  | 3 -> TOKEN_EQUAL
  | 4 -> TOKEN_TYPE
  | 5 -> TOKEN_MODULE
  | 6 -> TOKEN_PUB
  | 7 -> TOKEN_OPEN
  | 8 -> TOKEN_TH
  | 9 -> TOKEN_AX
  | 10 -> TOKEN_SQUARE
  | 11 -> TOKEN_PROOF
  | 12 -> TOKEN_COMMA
  | 13 -> TOKEN_RIGHT_BRACE
  | 14 -> TOKEN_LEFT_BRACE
  | 15 -> TOKEN_RIGHT_PAREN
  | 16 -> TOKEN_LEFT_PAREN
  | 17 -> TOKEN_NOT
  | 18 -> TOKEN_DIFFERS
  | 19 -> TOKEN_EQUIVALES
  | 20 -> TOKEN_FOLLOWS
  | 21 -> TOKEN_IMPLIES
  | 22 -> TOKEN_OR
  | 23 -> TOKEN_AND
  | 26 -> TOKEN_end_of_input
  | 24 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx: int) =
  match prodIdx with
  | 0 -> NONTERM__startstart
  | 1 -> NONTERM_expr
  | 2 -> NONTERM_expr
  | 3 -> NONTERM_expr
  | 4 -> NONTERM_expr
  | 5 -> NONTERM_expr
  | 6 -> NONTERM_expr
  | 7 -> NONTERM_expr
  | 8 -> NONTERM_expr
  | 9 -> NONTERM_expr
  | 10 -> NONTERM_identList
  | 11 -> NONTERM_identList
  | 12 -> NONTERM_hintOp
  | 13 -> NONTERM_hintOp
  | 14 -> NONTERM_hintOp
  | 15 -> NONTERM_hintOp
  | 16 -> NONTERM_hint
  | 17 -> NONTERM_transformer
  | 18 -> NONTERM_transformer
  | 19 -> NONTERM_steps
  | 20 -> NONTERM_steps
  | 21 -> NONTERM_proof
  | 22 -> NONTERM_law
  | 23 -> NONTERM_law
  | 24 -> NONTERM_open
  | 25 -> NONTERM_valueList
  | 26 -> NONTERM_valueList
  | 27 -> NONTERM_typeDecl
  | 28 -> NONTERM_statement
  | 29 -> NONTERM_statement
  | 30 -> NONTERM_statement
  | 31 -> NONTERM_statement
  | 32 -> NONTERM_statements
  | 33 -> NONTERM_statements
  | 34 -> NONTERM_module
  | 35 -> NONTERM_start
  | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 26
let _fsyacc_tagOfErrorTerminal = 24

// This function gets the name of a token as a string
let token_to_string (t: token) =
  match t with
  | EOF -> "EOF"
  | IDENT _ -> "IDENT"
  | BAR -> "BAR"
  | EQUAL -> "EQUAL"
  | TYPE -> "TYPE"
  | MODULE -> "MODULE"
  | PUB -> "PUB"
  | OPEN -> "OPEN"
  | TH -> "TH"
  | AX -> "AX"
  | SQUARE -> "SQUARE"
  | PROOF -> "PROOF"
  | COMMA -> "COMMA"
  | RIGHT_BRACE -> "RIGHT_BRACE"
  | LEFT_BRACE -> "LEFT_BRACE"
  | RIGHT_PAREN -> "RIGHT_PAREN"
  | LEFT_PAREN -> "LEFT_PAREN"
  | NOT -> "NOT"
  | DIFFERS -> "DIFFERS"
  | EQUIVALES -> "EQUIVALES"
  | FOLLOWS -> "FOLLOWS"
  | IMPLIES -> "IMPLIES"
  | OR -> "OR"
  | AND -> "AND"

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t: token) =
  match t with
  | EOF -> (null: System.Object)
  | IDENT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x
  | BAR -> (null: System.Object)
  | EQUAL -> (null: System.Object)
  | TYPE -> (null: System.Object)
  | MODULE -> (null: System.Object)
  | PUB -> (null: System.Object)
  | OPEN -> (null: System.Object)
  | TH -> (null: System.Object)
  | AX -> (null: System.Object)
  | SQUARE -> (null: System.Object)
  | PROOF -> (null: System.Object)
  | COMMA -> (null: System.Object)
  | RIGHT_BRACE -> (null: System.Object)
  | LEFT_BRACE -> (null: System.Object)
  | RIGHT_PAREN -> (null: System.Object)
  | LEFT_PAREN -> (null: System.Object)
  | NOT -> (null: System.Object)
  | DIFFERS -> (null: System.Object)
  | EQUIVALES -> (null: System.Object)
  | FOLLOWS -> (null: System.Object)
  | IMPLIES -> (null: System.Object)
  | OR -> (null: System.Object)
  | AND -> (null: System.Object)

let _fsyacc_gotos =
  [| 0us
     65535us
     16us
     65535us
     3us
     4us
     6us
     7us
     18us
     8us
     19us
     9us
     20us
     10us
     21us
     10us
     22us
     11us
     23us
     11us
     24us
     12us
     25us
     12us
     26us
     13us
     27us
     13us
     37us
     14us
     39us
     15us
     41us
     16us
     43us
     17us
     1us
     65535us
     33us
     29us
     1us
     65535us
     14us
     32us
     1us
     65535us
     14us
     35us
     1us
     65535us
     14us
     38us
     1us
     65535us
     15us
     37us
     1us
     65535us
     57us
     55us
     1us
     65535us
     57us
     54us
     1us
     65535us
     57us
     53us
     1us
     65535us
     52us
     47us
     1us
     65535us
     57us
     56us
     1us
     65535us
     57us
     58us
     1us
     65535us
     60us
     57us
     1us
     65535us
     0us
     61us
     1us
     65535us
     0us
     1us |]

let _fsyacc_sparseGotoTableRowOffsets =
  [| 0us
     1us
     18us
     20us
     22us
     24us
     26us
     28us
     30us
     32us
     34us
     36us
     38us
     40us
     42us
     44us |]

let _fsyacc_stateToProdIdxsTableElements =
  [| 1us
     0us
     1us
     0us
     1us
     1us
     1us
     2us
     7us
     2us
     4us
     5us
     6us
     7us
     8us
     9us
     1us
     2us
     1us
     3us
     7us
     3us
     4us
     5us
     6us
     7us
     8us
     9us
     7us
     4us
     4us
     5us
     6us
     7us
     8us
     9us
     7us
     4us
     5us
     5us
     6us
     7us
     8us
     9us
     7us
     4us
     5us
     6us
     6us
     7us
     8us
     9us
     7us
     4us
     5us
     6us
     7us
     7us
     8us
     9us
     7us
     4us
     5us
     6us
     7us
     8us
     8us
     9us
     7us
     4us
     5us
     6us
     7us
     8us
     9us
     9us
     7us
     4us
     5us
     6us
     7us
     8us
     9us
     20us
     7us
     4us
     5us
     6us
     7us
     8us
     9us
     21us
     7us
     4us
     5us
     6us
     7us
     8us
     9us
     22us
     7us
     4us
     5us
     6us
     7us
     8us
     9us
     23us
     1us
     4us
     1us
     5us
     1us
     6us
     2us
     6us
     12us
     1us
     7us
     2us
     7us
     13us
     1us
     8us
     2us
     8us
     14us
     1us
     9us
     2us
     9us
     15us
     1us
     10us
     2us
     11us
     16us
     1us
     11us
     1us
     11us
     1us
     16us
     1us
     16us
     1us
     16us
     1us
     17us
     1us
     18us
     2us
     20us
     21us
     1us
     20us
     1us
     21us
     1us
     22us
     1us
     22us
     1us
     23us
     1us
     23us
     1us
     24us
     1us
     24us
     1us
     25us
     2us
     26us
     27us
     1us
     26us
     1us
     26us
     1us
     27us
     1us
     27us
     1us
     27us
     1us
     28us
     1us
     29us
     1us
     30us
     1us
     31us
     2us
     33us
     34us
     1us
     33us
     1us
     34us
     1us
     34us
     1us
     35us |]

let _fsyacc_stateToProdIdxsTableRowOffsets =
  [| 0us
     2us
     4us
     6us
     8us
     16us
     18us
     20us
     28us
     36us
     44us
     52us
     60us
     68us
     76us
     84us
     92us
     100us
     108us
     110us
     112us
     114us
     117us
     119us
     122us
     124us
     127us
     129us
     132us
     134us
     137us
     139us
     141us
     143us
     145us
     147us
     149us
     151us
     154us
     156us
     158us
     160us
     162us
     164us
     166us
     168us
     170us
     172us
     175us
     177us
     179us
     181us
     183us
     185us
     187us
     189us
     191us
     193us
     196us
     198us
     200us
     202us |]

let _fsyacc_action_rows = 62

let _fsyacc_actionTableElements =
  [| 1us
     32768us
     5us
     59us
     0us
     49152us
     0us
     16385us
     3us
     32768us
     1us
     2us
     16us
     3us
     17us
     6us
     7us
     32768us
     16us
     5us
     18us
     26us
     19us
     24us
     20us
     22us
     21us
     20us
     22us
     19us
     23us
     18us
     0us
     16386us
     3us
     32768us
     1us
     2us
     16us
     3us
     17us
     6us
     0us
     16387us
     0us
     16388us
     0us
     16389us
     2us
     16390us
     22us
     19us
     23us
     18us
     2us
     16391us
     22us
     19us
     23us
     18us
     4us
     16392us
     20us
     22us
     21us
     20us
     22us
     19us
     23us
     18us
     4us
     16393us
     20us
     22us
     21us
     20us
     22us
     19us
     23us
     18us
     7us
     32768us
     10us
     36us
     18us
     27us
     19us
     25us
     20us
     23us
     21us
     21us
     22us
     19us
     23us
     18us
     6us
     16403us
     18us
     26us
     19us
     24us
     20us
     22us
     21us
     20us
     22us
     19us
     23us
     18us
     6us
     16406us
     18us
     26us
     19us
     24us
     20us
     22us
     21us
     20us
     22us
     19us
     23us
     18us
     6us
     16407us
     18us
     26us
     19us
     24us
     20us
     22us
     21us
     20us
     22us
     19us
     23us
     18us
     3us
     32768us
     1us
     2us
     16us
     3us
     17us
     6us
     3us
     32768us
     1us
     2us
     16us
     3us
     17us
     6us
     3us
     32768us
     1us
     2us
     16us
     3us
     17us
     6us
     3us
     16396us
     1us
     2us
     16us
     3us
     17us
     6us
     3us
     32768us
     1us
     2us
     16us
     3us
     17us
     6us
     3us
     16397us
     1us
     2us
     16us
     3us
     17us
     6us
     3us
     32768us
     1us
     2us
     16us
     3us
     17us
     6us
     3us
     16398us
     1us
     2us
     16us
     3us
     17us
     6us
     3us
     32768us
     1us
     2us
     16us
     3us
     17us
     6us
     3us
     16399us
     1us
     2us
     16us
     3us
     17us
     6us
     0us
     16394us
     2us
     32768us
     12us
     30us
     13us
     34us
     1us
     32768us
     1us
     31us
     0us
     16395us
     1us
     32768us
     14us
     33us
     1us
     32768us
     1us
     28us
     0us
     16400us
     0us
     16401us
     0us
     16402us
     3us
     16405us
     1us
     2us
     16us
     3us
     17us
     6us
     0us
     16404us
     3us
     32768us
     1us
     2us
     16us
     3us
     17us
     6us
     1us
     32768us
     1us
     41us
     3us
     32768us
     1us
     2us
     16us
     3us
     17us
     6us
     1us
     32768us
     1us
     43us
     3us
     32768us
     1us
     2us
     16us
     3us
     17us
     6us
     1us
     32768us
     1us
     45us
     0us
     16408us
     0us
     16409us
     1us
     16411us
     2us
     48us
     1us
     32768us
     1us
     49us
     0us
     16410us
     1us
     32768us
     1us
     51us
     1us
     32768us
     3us
     52us
     1us
     32768us
     1us
     46us
     0us
     16412us
     0us
     16413us
     0us
     16414us
     0us
     16415us
     5us
     16418us
     4us
     50us
     7us
     44us
     8us
     40us
     9us
     42us
     11us
     39us
     0us
     16417us
     1us
     32768us
     1us
     60us
     0us
     16416us
     0us
     16419us |]

let _fsyacc_actionTableRowOffsets =
  [| 0us
     2us
     3us
     4us
     8us
     16us
     17us
     21us
     22us
     23us
     24us
     27us
     30us
     35us
     40us
     48us
     55us
     62us
     69us
     73us
     77us
     81us
     85us
     89us
     93us
     97us
     101us
     105us
     109us
     110us
     113us
     115us
     116us
     118us
     120us
     121us
     122us
     123us
     127us
     128us
     132us
     134us
     138us
     140us
     144us
     146us
     147us
     148us
     150us
     152us
     153us
     155us
     157us
     159us
     160us
     161us
     162us
     163us
     169us
     170us
     172us
     173us |]

let _fsyacc_reductionSymbolCounts =
  [| 1us
     1us
     3us
     2us
     3us
     3us
     3us
     3us
     3us
     3us
     1us
     3us
     1us
     1us
     1us
     1us
     4us
     1us
     1us
     0us
     3us
     3us
     3us
     3us
     2us
     1us
     3us
     4us
     1us
     1us
     1us
     1us
     0us
     2us
     3us
     1us |]

let _fsyacc_productionToNonTerminalTable =
  [| 0us
     1us
     1us
     1us
     1us
     1us
     1us
     1us
     1us
     1us
     2us
     2us
     3us
     3us
     3us
     3us
     4us
     5us
     5us
     6us
     6us
     7us
     8us
     8us
     9us
     10us
     10us
     11us
     12us
     12us
     12us
     12us
     13us
     13us
     14us
     15us |]

let _fsyacc_immediateActions =
  [| 65535us
     49152us
     16385us
     65535us
     65535us
     16386us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     16394us
     65535us
     65535us
     16395us
     65535us
     65535us
     16400us
     16401us
     16402us
     65535us
     16404us
     65535us
     65535us
     65535us
     65535us
     65535us
     65535us
     16408us
     16409us
     65535us
     65535us
     16410us
     65535us
     65535us
     65535us
     16412us
     16413us
     16414us
     16415us
     65535us
     16417us
     65535us
     65535us
     16419us |]

let _fsyacc_reductions =
  lazy
    [| (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> Module in

         Microsoft.FSharp.Core.Operators.box (
           (raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))): 'gentype__startstart
         ))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> string in Microsoft.FSharp.Core.Operators.box ((Ident _1): 'gentype_expr))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _2 = parseState.GetInput(2) :?> 'gentype_expr in Microsoft.FSharp.Core.Operators.box ((_2): 'gentype_expr))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _2 = parseState.GetInput(2) :?> 'gentype_expr in
         Microsoft.FSharp.Core.Operators.box ((Not _2): 'gentype_expr))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_expr in
         let _3 = parseState.GetInput(3) :?> 'gentype_expr in
         Microsoft.FSharp.Core.Operators.box ((And { left = _1; right = _3 }): 'gentype_expr))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_expr in
         let _3 = parseState.GetInput(3) :?> 'gentype_expr in
         Microsoft.FSharp.Core.Operators.box ((Or { left = _1; right = _3 }): 'gentype_expr))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_expr in
         let _3 = parseState.GetInput(3) :?> 'gentype_expr in
         Microsoft.FSharp.Core.Operators.box ((Implies { left = _1; right = _3 }): 'gentype_expr))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_expr in
         let _3 = parseState.GetInput(3) :?> 'gentype_expr in
         Microsoft.FSharp.Core.Operators.box ((Follows { left = _1; right = _3 }): 'gentype_expr))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_expr in
         let _3 = parseState.GetInput(3) :?> 'gentype_expr in
         Microsoft.FSharp.Core.Operators.box ((Equivales { left = _1; right = _3 }): 'gentype_expr))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_expr in
         let _3 = parseState.GetInput(3) :?> 'gentype_expr in
         Microsoft.FSharp.Core.Operators.box ((Differs { left = _1; right = _3 }): 'gentype_expr))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> string in
         Microsoft.FSharp.Core.Operators.box (([ _1 ]): 'gentype_identList))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_identList in
         let _3 = parseState.GetInput(3) :?> string in
         Microsoft.FSharp.Core.Operators.box ((_3 :: _1): 'gentype_identList))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         Microsoft.FSharp.Core.Operators.box ((HintImplies): 'gentype_hintOp))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         Microsoft.FSharp.Core.Operators.box ((HintFollows): 'gentype_hintOp))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         Microsoft.FSharp.Core.Operators.box ((HintEquivales): 'gentype_hintOp))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         Microsoft.FSharp.Core.Operators.box ((HintDiffers): 'gentype_hintOp))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_hintOp in
         let _3 = parseState.GetInput(3) :?> 'gentype_identList in

         Microsoft.FSharp.Core.Operators.box (
           ({ operator = _1
              lawNames = List.rev _3 })
           : 'gentype_hint
         ))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_hint in
         Microsoft.FSharp.Core.Operators.box ((Trans _1): 'gentype_transformer))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         Microsoft.FSharp.Core.Operators.box ((End): 'gentype_transformer))
       (fun (parseState: FSharp.Text.Parsing.IParseState) -> Microsoft.FSharp.Core.Operators.box (([]): 'gentype_steps))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_steps in
         let _2 = parseState.GetInput(2) :?> 'gentype_expr in
         let _3 = parseState.GetInput(3) :?> 'gentype_transformer in
         Microsoft.FSharp.Core.Operators.box (({ expr = _2; trans = _3 } :: _1): 'gentype_steps))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _2 = parseState.GetInput(2) :?> 'gentype_expr in
         let _3 = parseState.GetInput(3) :?> 'gentype_steps in
         Microsoft.FSharp.Core.Operators.box (({ thesis = _2; steps = List.rev _3 }): 'gentype_proof))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _2 = parseState.GetInput(2) :?> string in
         let _3 = parseState.GetInput(3) :?> 'gentype_expr in
         Microsoft.FSharp.Core.Operators.box ((Theorem { name = _2; expr = _3 }): 'gentype_law))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _2 = parseState.GetInput(2) :?> string in
         let _3 = parseState.GetInput(3) :?> 'gentype_expr in
         Microsoft.FSharp.Core.Operators.box ((Axiom { name = _2; expr = _3 }): 'gentype_law))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _2 = parseState.GetInput(2) :?> string in Microsoft.FSharp.Core.Operators.box ((Open _2): 'gentype_open))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> string in
         Microsoft.FSharp.Core.Operators.box (([ Value _1 ]): 'gentype_valueList))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_valueList in
         let _3 = parseState.GetInput(3) :?> string in
         Microsoft.FSharp.Core.Operators.box (((Value _3) :: _1): 'gentype_valueList))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _2 = parseState.GetInput(2) :?> string in
         let _4 = parseState.GetInput(4) :?> 'gentype_valueList in
         Microsoft.FSharp.Core.Operators.box (({ name = _2; values = List.rev _4 }): 'gentype_typeDecl))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_open in
         Microsoft.FSharp.Core.Operators.box ((_1): 'gentype_statement))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_law in
         Microsoft.FSharp.Core.Operators.box ((Law _1): 'gentype_statement))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_proof in
         Microsoft.FSharp.Core.Operators.box ((Proof _1): 'gentype_statement))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_typeDecl in
         Microsoft.FSharp.Core.Operators.box ((TypeDecl _1): 'gentype_statement))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         Microsoft.FSharp.Core.Operators.box (([]): 'gentype_statements))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_statements in
         let _2 = parseState.GetInput(2) :?> 'gentype_statement in
         Microsoft.FSharp.Core.Operators.box ((_2 :: _1): 'gentype_statements))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _2 = parseState.GetInput(2) :?> string in
         let _3 = parseState.GetInput(3) :?> 'gentype_statements in
         Microsoft.FSharp.Core.Operators.box (({ name = _2; statements = _3 }): 'gentype_module))
       (fun (parseState: FSharp.Text.Parsing.IParseState) ->
         let _1 = parseState.GetInput(1) :?> 'gentype_module in Microsoft.FSharp.Core.Operators.box ((_1): Module)) |]

let tables: FSharp.Text.Parsing.Tables<_> =
  { reductions = _fsyacc_reductions.Value
    endOfInputTag = _fsyacc_endOfInputTag
    tagOfToken = tagOfToken
    dataOfToken = _fsyacc_dataOfToken
    actionTableElements = _fsyacc_actionTableElements
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts
    immediateActions = _fsyacc_immediateActions
    gotos = _fsyacc_gotos
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal
    parseError =
      (fun (ctxt: FSharp.Text.Parsing.ParseErrorContext<_>) ->
        match parse_error_rich with
        | Some f -> f ctxt
        | None -> parse_error ctxt.Message)
    numTerminals = 27
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable }

let engine lexer lexbuf startState =
  tables.Interpret(lexer, lexbuf, startState)

let start lexer lexbuf : Module = engine lexer lexbuf 0 :?> _
