// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "Parser.fsy"

    open Language

# 10 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | IDENT of (string)
  | BULLET
  | ALPHA
  | MU
  | ARROW
  | TYPEOF
  | BAR
  | EQUAL
  | SET
  | MODULE
  | PUB
  | OPEN
  | TH
  | AX
  | SQUARE
  | PROOF
  | COMMA
  | RIGHT_BRACE
  | LEFT_BRACE
  | RIGHT_PAREN
  | LEFT_PAREN
  | UN_OP of (string)
  | BIN_OP of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_IDENT
    | TOKEN_BULLET
    | TOKEN_ALPHA
    | TOKEN_MU
    | TOKEN_ARROW
    | TOKEN_TYPEOF
    | TOKEN_BAR
    | TOKEN_EQUAL
    | TOKEN_SET
    | TOKEN_MODULE
    | TOKEN_PUB
    | TOKEN_OPEN
    | TOKEN_TH
    | TOKEN_AX
    | TOKEN_SQUARE
    | TOKEN_PROOF
    | TOKEN_COMMA
    | TOKEN_RIGHT_BRACE
    | TOKEN_LEFT_BRACE
    | TOKEN_RIGHT_PAREN
    | TOKEN_LEFT_PAREN
    | TOKEN_UN_OP
    | TOKEN_BIN_OP
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_expr
    | NONTERM_identList
    | NONTERM_hint
    | NONTERM_transformer
    | NONTERM_steps
    | NONTERM_proof
    | NONTERM_law
    | NONTERM_open
    | NONTERM_valueList
    | NONTERM_setDecl
    | NONTERM_signature
    | NONTERM_funcIdent
    | NONTERM_typeOfDecl
    | NONTERM_statement
    | NONTERM_statements
    | NONTERM_module
    | NONTERM_start

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | IDENT _ -> 1 
  | BULLET  -> 2 
  | ALPHA  -> 3 
  | MU  -> 4 
  | ARROW  -> 5 
  | TYPEOF  -> 6 
  | BAR  -> 7 
  | EQUAL  -> 8 
  | SET  -> 9 
  | MODULE  -> 10 
  | PUB  -> 11 
  | OPEN  -> 12 
  | TH  -> 13 
  | AX  -> 14 
  | SQUARE  -> 15 
  | PROOF  -> 16 
  | COMMA  -> 17 
  | RIGHT_BRACE  -> 18 
  | LEFT_BRACE  -> 19 
  | RIGHT_PAREN  -> 20 
  | LEFT_PAREN  -> 21 
  | UN_OP _ -> 22 
  | BIN_OP _ -> 23 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_IDENT 
  | 2 -> TOKEN_BULLET 
  | 3 -> TOKEN_ALPHA 
  | 4 -> TOKEN_MU 
  | 5 -> TOKEN_ARROW 
  | 6 -> TOKEN_TYPEOF 
  | 7 -> TOKEN_BAR 
  | 8 -> TOKEN_EQUAL 
  | 9 -> TOKEN_SET 
  | 10 -> TOKEN_MODULE 
  | 11 -> TOKEN_PUB 
  | 12 -> TOKEN_OPEN 
  | 13 -> TOKEN_TH 
  | 14 -> TOKEN_AX 
  | 15 -> TOKEN_SQUARE 
  | 16 -> TOKEN_PROOF 
  | 17 -> TOKEN_COMMA 
  | 18 -> TOKEN_RIGHT_BRACE 
  | 19 -> TOKEN_LEFT_BRACE 
  | 20 -> TOKEN_RIGHT_PAREN 
  | 21 -> TOKEN_LEFT_PAREN 
  | 22 -> TOKEN_UN_OP 
  | 23 -> TOKEN_BIN_OP 
  | 26 -> TOKEN_end_of_input
  | 24 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_expr 
    | 2 -> NONTERM_expr 
    | 3 -> NONTERM_expr 
    | 4 -> NONTERM_expr 
    | 5 -> NONTERM_identList 
    | 6 -> NONTERM_identList 
    | 7 -> NONTERM_hint 
    | 8 -> NONTERM_transformer 
    | 9 -> NONTERM_transformer 
    | 10 -> NONTERM_steps 
    | 11 -> NONTERM_steps 
    | 12 -> NONTERM_proof 
    | 13 -> NONTERM_law 
    | 14 -> NONTERM_law 
    | 15 -> NONTERM_open 
    | 16 -> NONTERM_valueList 
    | 17 -> NONTERM_valueList 
    | 18 -> NONTERM_setDecl 
    | 19 -> NONTERM_signature 
    | 20 -> NONTERM_signature 
    | 21 -> NONTERM_funcIdent 
    | 22 -> NONTERM_funcIdent 
    | 23 -> NONTERM_funcIdent 
    | 24 -> NONTERM_typeOfDecl 
    | 25 -> NONTERM_statement 
    | 26 -> NONTERM_statement 
    | 27 -> NONTERM_statement 
    | 28 -> NONTERM_statement 
    | 29 -> NONTERM_statement 
    | 30 -> NONTERM_statements 
    | 31 -> NONTERM_statements 
    | 32 -> NONTERM_module 
    | 33 -> NONTERM_start 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 26 
let _fsyacc_tagOfErrorTerminal = 24

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | IDENT _ -> "IDENT" 
  | BULLET  -> "BULLET" 
  | ALPHA  -> "ALPHA" 
  | MU  -> "MU" 
  | ARROW  -> "ARROW" 
  | TYPEOF  -> "TYPEOF" 
  | BAR  -> "BAR" 
  | EQUAL  -> "EQUAL" 
  | SET  -> "SET" 
  | MODULE  -> "MODULE" 
  | PUB  -> "PUB" 
  | OPEN  -> "OPEN" 
  | TH  -> "TH" 
  | AX  -> "AX" 
  | SQUARE  -> "SQUARE" 
  | PROOF  -> "PROOF" 
  | COMMA  -> "COMMA" 
  | RIGHT_BRACE  -> "RIGHT_BRACE" 
  | LEFT_BRACE  -> "LEFT_BRACE" 
  | RIGHT_PAREN  -> "RIGHT_PAREN" 
  | LEFT_PAREN  -> "LEFT_PAREN" 
  | UN_OP _ -> "UN_OP" 
  | BIN_OP _ -> "BIN_OP" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | IDENT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | BULLET  -> (null : System.Object) 
  | ALPHA  -> (null : System.Object) 
  | MU  -> (null : System.Object) 
  | ARROW  -> (null : System.Object) 
  | TYPEOF  -> (null : System.Object) 
  | BAR  -> (null : System.Object) 
  | EQUAL  -> (null : System.Object) 
  | SET  -> (null : System.Object) 
  | MODULE  -> (null : System.Object) 
  | PUB  -> (null : System.Object) 
  | OPEN  -> (null : System.Object) 
  | TH  -> (null : System.Object) 
  | AX  -> (null : System.Object) 
  | SQUARE  -> (null : System.Object) 
  | PROOF  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | RIGHT_BRACE  -> (null : System.Object) 
  | LEFT_BRACE  -> (null : System.Object) 
  | RIGHT_PAREN  -> (null : System.Object) 
  | LEFT_PAREN  -> (null : System.Object) 
  | UN_OP _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | BIN_OP _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us;65535us;8us;65535us;3us;4us;6us;7us;13us;8us;14us;8us;23us;9us;25us;10us;27us;11us;29us;12us;1us;65535us;19us;16us;1us;65535us;9us;21us;1us;65535us;9us;24us;1us;65535us;10us;23us;1us;65535us;56us;53us;1us;65535us;56us;52us;1us;65535us;56us;51us;1us;65535us;39us;33us;1us;65535us;56us;54us;1us;65535us;50us;42us;1us;65535us;48us;49us;1us;65535us;56us;55us;1us;65535us;56us;57us;1us;65535us;59us;56us;1us;65535us;0us;60us;1us;65535us;0us;1us;|]
let _fsyacc_sparseGotoTableRowOffsets = [|0us;1us;10us;12us;14us;16us;18us;20us;22us;24us;26us;28us;30us;32us;34us;36us;38us;40us;|]
let _fsyacc_stateToProdIdxsTableElements = [| 1us;0us;1us;0us;1us;1us;1us;2us;2us;2us;4us;1us;2us;1us;3us;2us;3us;4us;2us;4us;4us;2us;4us;11us;2us;4us;12us;2us;4us;13us;2us;4us;14us;1us;4us;2us;4us;7us;1us;5us;2us;6us;7us;1us;6us;1us;6us;1us;7us;1us;7us;1us;8us;1us;9us;2us;11us;12us;1us;11us;1us;12us;1us;13us;1us;13us;1us;14us;1us;14us;1us;15us;1us;15us;1us;16us;2us;17us;18us;1us;17us;1us;17us;1us;18us;1us;18us;1us;18us;1us;18us;1us;18us;1us;19us;2us;20us;24us;1us;20us;1us;20us;1us;21us;1us;22us;1us;23us;1us;24us;1us;24us;1us;24us;1us;25us;1us;26us;1us;27us;1us;28us;1us;29us;2us;31us;32us;1us;31us;1us;32us;1us;32us;1us;33us;|]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us;2us;4us;6us;8us;11us;13us;15us;18us;21us;24us;27us;30us;33us;35us;38us;40us;43us;45us;47us;49us;51us;53us;55us;58us;60us;62us;64us;66us;68us;70us;72us;74us;76us;79us;81us;83us;85us;87us;89us;91us;93us;95us;98us;100us;102us;104us;106us;108us;110us;112us;114us;116us;118us;120us;122us;124us;127us;129us;131us;133us;|]
let _fsyacc_action_rows = 61
let _fsyacc_actionTableElements = [|1us;32768us;10us;58us;0us;49152us;0us;16385us;3us;32768us;1us;2us;21us;3us;22us;6us;2us;32768us;21us;5us;23us;13us;0us;16386us;3us;32768us;1us;2us;21us;3us;22us;6us;0us;16387us;0us;16388us;2us;32768us;15us;22us;23us;14us;1us;16394us;23us;13us;1us;16397us;23us;13us;1us;16398us;23us;13us;3us;32768us;1us;2us;21us;3us;22us;6us;4us;32768us;1us;2us;19us;19us;21us;3us;22us;6us;0us;16389us;2us;32768us;17us;17us;18us;20us;1us;32768us;1us;18us;0us;16390us;1us;32768us;1us;15us;0us;16391us;0us;16392us;0us;16393us;3us;16396us;1us;2us;21us;3us;22us;6us;0us;16395us;3us;32768us;1us;2us;21us;3us;22us;6us;1us;32768us;1us;27us;3us;32768us;1us;2us;21us;3us;22us;6us;1us;32768us;1us;29us;3us;32768us;1us;2us;21us;3us;22us;6us;1us;32768us;1us;31us;0us;16399us;0us;16400us;2us;32768us;17us;34us;18us;40us;1us;32768us;1us;35us;0us;16401us;1us;32768us;1us;37us;1us;32768us;8us;38us;1us;32768us;19us;39us;1us;32768us;1us;32us;0us;16402us;0us;16403us;1us;16408us;5us;43us;1us;32768us;1us;44us;0us;16404us;0us;16405us;0us;16406us;0us;16407us;3us;32768us;1us;45us;22us;46us;23us;47us;1us;32768us;8us;50us;1us;32768us;1us;41us;0us;16409us;0us;16410us;0us;16411us;0us;16412us;0us;16413us;6us;16416us;6us;48us;9us;36us;12us;30us;13us;26us;14us;28us;16us;25us;0us;16415us;1us;32768us;1us;59us;0us;16414us;0us;16417us;|]
let _fsyacc_actionTableRowOffsets = [|0us;2us;3us;4us;8us;11us;12us;16us;17us;18us;21us;23us;25us;27us;31us;36us;37us;40us;42us;43us;45us;46us;47us;48us;52us;53us;57us;59us;63us;65us;69us;71us;72us;73us;76us;78us;79us;81us;83us;85us;87us;88us;89us;91us;93us;94us;95us;96us;97us;101us;103us;105us;106us;107us;108us;109us;110us;117us;118us;120us;121us;|]
let _fsyacc_reductionSymbolCounts = [|1us;1us;3us;2us;3us;1us;3us;4us;1us;1us;0us;3us;3us;3us;3us;2us;1us;3us;6us;1us;3us;1us;1us;1us;4us;1us;1us;1us;1us;1us;0us;2us;3us;1us;|]
let _fsyacc_productionToNonTerminalTable = [|0us;1us;1us;1us;1us;2us;2us;3us;4us;4us;5us;5us;6us;7us;7us;8us;9us;9us;10us;11us;11us;12us;12us;12us;13us;14us;14us;14us;14us;14us;15us;15us;16us;17us;|]
let _fsyacc_immediateActions = [|65535us;49152us;16385us;65535us;65535us;16386us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;16389us;65535us;65535us;16390us;65535us;16391us;16392us;16393us;65535us;16395us;65535us;65535us;65535us;65535us;65535us;65535us;16399us;16400us;65535us;65535us;16401us;65535us;65535us;65535us;65535us;16402us;16403us;65535us;65535us;16404us;16405us;16406us;16407us;65535us;65535us;65535us;16409us;16410us;16411us;16412us;16413us;65535us;16415us;65535us;65535us;16417us;|]
let _fsyacc_reductions = lazy [|
# 253 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> Module in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : 'gentype__startstart));
# 262 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "Parser.fsy"
                                   Ident _1 
                   )
# 47 "Parser.fsy"
                 : 'gentype_expr));
# 273 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "Parser.fsy"
                                                        _2 
                   )
# 48 "Parser.fsy"
                 : 'gentype_expr));
# 284 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            let _2 = parseState.GetInput(2) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "Parser.fsy"
                                        Unary {operator = _1; expr = _2 } 
                   )
# 49 "Parser.fsy"
                 : 'gentype_expr));
# 296 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expr in
            let _2 = parseState.GetInput(2) :?> string in
            let _3 = parseState.GetInput(3) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 50 "Parser.fsy"
                                              Binary { operator = _2; left = _1; right = _3 } 
                   )
# 50 "Parser.fsy"
                 : 'gentype_expr));
# 309 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "Parser.fsy"
                                   [_1] 
                   )
# 53 "Parser.fsy"
                 : 'gentype_identList));
# 320 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_identList in
            let _3 = parseState.GetInput(3) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "Parser.fsy"
                                                   _3 :: _1 
                   )
# 54 "Parser.fsy"
                 : 'gentype_identList));
# 332 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            let _3 = parseState.GetInput(3) :?> 'gentype_identList in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "Parser.fsy"
                                                                     {operator = _1; lawNames = List.rev _3 } 
                   )
# 57 "Parser.fsy"
                 : 'gentype_hint));
# 344 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_hint in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 60 "Parser.fsy"
                                  Trans _1 
                   )
# 60 "Parser.fsy"
                 : 'gentype_transformer));
# 355 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "Parser.fsy"
                                    End 
                   )
# 61 "Parser.fsy"
                 : 'gentype_transformer));
# 365 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 64 "Parser.fsy"
                             [] 
                   )
# 64 "Parser.fsy"
                 : 'gentype_steps));
# 375 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_steps in
            let _2 = parseState.GetInput(2) :?> 'gentype_expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_transformer in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "Parser.fsy"
                                                    { expr = _2; trans = _3 } :: _1 
                   )
# 65 "Parser.fsy"
                 : 'gentype_steps));
# 388 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_steps in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 68 "Parser.fsy"
                                              {thesis = _2; steps = List.rev _3 } 
                   )
# 68 "Parser.fsy"
                 : 'gentype_proof));
# 400 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> string in
            let _3 = parseState.GetInput(3) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 71 "Parser.fsy"
                                           Theorem {name = _2; expr = _3 } 
                   )
# 71 "Parser.fsy"
                 : 'gentype_law));
# 412 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> string in
            let _3 = parseState.GetInput(3) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 72 "Parser.fsy"
                                           Axiom {name = _2; expr = _3} 
                   )
# 72 "Parser.fsy"
                 : 'gentype_law));
# 424 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 75 "Parser.fsy"
                                        Open _2 
                   )
# 75 "Parser.fsy"
                 : 'gentype_open));
# 435 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 78 "Parser.fsy"
                                   [Value _1] 
                   )
# 78 "Parser.fsy"
                 : 'gentype_valueList));
# 446 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_valueList in
            let _3 = parseState.GetInput(3) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 79 "Parser.fsy"
                                                   (Value _3) :: _1 
                   )
# 79 "Parser.fsy"
                 : 'gentype_valueList));
# 458 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> string in
            let _5 = parseState.GetInput(5) :?> 'gentype_valueList in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 82 "Parser.fsy"
                                                                              {name = _2; values = List.rev _5} 
                   )
# 82 "Parser.fsy"
                 : 'gentype_setDecl));
# 470 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 85 "Parser.fsy"
                                   [_1] 
                   )
# 85 "Parser.fsy"
                 : 'gentype_signature));
# 481 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_signature in
            let _3 = parseState.GetInput(3) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 86 "Parser.fsy"
                                                   _3 :: _1 
                   )
# 86 "Parser.fsy"
                 : 'gentype_signature));
# 493 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 89 "Parser.fsy"
                                   _1 
                   )
# 89 "Parser.fsy"
                 : 'gentype_funcIdent));
# 504 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 90 "Parser.fsy"
                                   _1 
                   )
# 90 "Parser.fsy"
                 : 'gentype_funcIdent));
# 515 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 91 "Parser.fsy"
                                    _1 
                   )
# 91 "Parser.fsy"
                 : 'gentype_funcIdent));
# 526 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_funcIdent in
            let _4 = parseState.GetInput(4) :?> 'gentype_signature in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 94 "Parser.fsy"
                                                              {func = _2; signature = List.rev _4 }
                   )
# 94 "Parser.fsy"
                 : 'gentype_typeOfDecl));
# 538 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_open in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 97 "Parser.fsy"
                                  _1 
                   )
# 97 "Parser.fsy"
                 : 'gentype_statement));
# 549 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_law in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 98 "Parser.fsy"
                                 Law _1 
                   )
# 98 "Parser.fsy"
                 : 'gentype_statement));
# 560 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_proof in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 99 "Parser.fsy"
                                   Proof _1 
                   )
# 99 "Parser.fsy"
                 : 'gentype_statement));
# 571 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_setDecl in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 100 "Parser.fsy"
                                     SetDecl _1 
                   )
# 100 "Parser.fsy"
                 : 'gentype_statement));
# 582 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_typeOfDecl in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 101 "Parser.fsy"
                                        TypeOfDecl _1 
                   )
# 101 "Parser.fsy"
                 : 'gentype_statement));
# 593 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 105 "Parser.fsy"
                             [] 
                   )
# 105 "Parser.fsy"
                 : 'gentype_statements));
# 603 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_statements in
            let _2 = parseState.GetInput(2) :?> 'gentype_statement in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 106 "Parser.fsy"
                                                  _2 :: _1 
                   )
# 106 "Parser.fsy"
                 : 'gentype_statements));
# 615 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> string in
            let _3 = parseState.GetInput(3) :?> 'gentype_statements in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 109 "Parser.fsy"
                                                     {name = _2; statements = _3 } 
                   )
# 109 "Parser.fsy"
                 : 'gentype_module));
# 627 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_module in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 111 "Parser.fsy"
                                     _1 
                   )
# 111 "Parser.fsy"
                 : Module));
|]
# 639 "Parser.fs"
let tables : FSharp.Text.Parsing.Tables<_> = 
  { reductions = _fsyacc_reductions.Value;
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 27;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = tables.Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : Module =
    engine lexer lexbuf 0 :?> _
